name: GetMoarFediverse

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  moar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: g3rv4/GetMoarFediverse@main
        with:
          config_file: ${{ github.workspace }}/config.json
          api_key: ${{ secrets.FAKERELAY_APIKEY }}
      - name: Keep workflow alive
        uses: gautamkrishnar/keepalive-workflow@v2
